# -*- coding: utf-8 -*-
"""Crawling tweet Kompascom dan Pikiranrakyat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cw_OXo7OmG88W_uPOsIJC7Po-n2MBAzR

Melakukan crawling data dari twitter dan menyimpan dalam dataframe
"""

import tweepy
import csv
import pandas as pd

consumer_key = "BNg80L4ns3FSYX7zdrycuL4V8"
consumer_secret = "j5u0tOCPR3Yu5NpIzTrw2KlQJMu2LfOm0bcrSa5cHtRJDjjkFg"
access_token = "726088504904585216-qWViVLKZioS4eGXswkk7La2sPQfVNV0"
access_token_secret = "0DO4fLJMuVGTx77LARtHoUU1u299yrj3lQL2EavOvkana"


# In[3]:

# handler autentikasi
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth)


# In[4]:

# Melakukan looping untuk hasil tweet dalam full text
df = pd.DataFrame()
portals = ['kompascom', 'pikiran_rakyat']
for portal in portals:
    berita = []
    tweets = api.user_timeline(id=portal, count=500, tweet_mode='extended')
    for tweet in tweets:
        berita.append(tweet.full_text)
    df[portal] = berita
print(df)


# In[6]:
# memberi nama kolom dengan lowercase
df.rename(columns={'pikiran_rakyat' : 'Pikiranrakyat', 'kompascom' : 'Kompascom'}, inplace=True)
print(df)